
vim.cmd(['autocmd FileType python map <buffer> <F9> :w<CR>:exec "!python3" shellescape(@%, 1)<CR>'])
-- vim.cmd(['autocmd FileType python imap <buffer> <F9> <esc>:w<CR>:exec '!python3' shellescape(@%, 1)<CR>'])
-- vim.cmd(['autocmd FileType javascript map <buffer> <F9> :w<CR>:!node %<CR>'])
-- vim.cmd(['autocmd FileType javascript imap <buffer> <F9> <esc>:w<CR>:!node %<CR>'])
-- vim.cmd(['autocmd FileType sh map <buffer> <F9> :w<CR>:!/bin/bash %<CR>'])
-- vim.cmd(['autocmd FileType sh imap <buffer> <F9> <esc>:w<CR>:!/bin/bash %<CR>'])
-- vim.cmd(['autocmd FileType c imap <buffer> <F9> <esc>:w<CR>:!gcc % -o %<  && ./%<<CR>'])
-- vim.cmd(['autocmd FileType c map <buffer> <F9> <esc>:w<CR>:!gcc % -o %<  && ./%<<CR>'])
-- vim.cmd(['autocmd FileType cpp map <buffer> <F9> <esc>:w<CR>:!make<CR>'])
-- vim.cmd(['autocmd FileType cpp map <buffer> <F9> <esc>:w<CR>:!make<CR>'])
-- vim.cmd(['autocmd FileType perl map <buffer> <F9> :w<CR>:!/usr/bin/perl %<CR>'])
-- vim.cmd(['autocmd FileType perl imap <buffer> <F9> <esc>:w<CR>:!/usr/bin/perl %<CR>'])
-- vim.cmd(['autocmd FileType typescript imap <buffer> <F9> <esc>:w<CR>:!tsc % && node %<.js<CR>'])
-- vim.cmd(['autocmd FileType typescript map <buffer> <F9> <esc>:w<CR>:!tsc % && node %<.js<CR>'])
-- vim.cmd(['autocmd FileType rust imap <buffer> <F9> <esc>:w<CR>:!cargo run<CR>'])
-- vim.cmd(['autocmd FileType rust map <buffer> <F9> <esc>:w<CR>:!cargo run<CR>'])
